### ISSUE TITLE
I donk really know why travis dont check my proyect

### ISSUE THREAD

**Issue by McGredu** [UNIZAR-30246-WebEngineering/lab4-websockets#31]
I`ve done the practice but travis dont want to check the proyect, ive made the same thing i did in all the other proyect.

The poryect works fine, the gradle check command seems correct and the test works correctly, the only problem is travis.

Maybe you know what is the problem.

**Comment by fjlopez** [comment]
Your must use `https://api.travis-ci.org/SureSRM/lab4-websockets.svg?branch=test` which produces ![https://api.travis-ci.org/SureSRM/lab4-websockets.svg?branch=test](https://api.travis-ci.org/SureSRM/lab4-websockets.svg?branch=test).

**Comment by fjlopez** [comment]
The problem is hidden in plain sight: replace `suresrm` by `SureSRM` and the problem is fixed.
